# permissions for end users to edit openstackplaybookgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackplaybookgenerator-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackplaybookgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackplaybookgenerators/status
  verbs:
  - get
