# permissions for end users to view openstackephemeralheats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackephemeralheat-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackephemeralheats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackephemeralheats/status
  verbs:
  - get
