# permissions for end users to view openstackplaybookgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackplaybookgenerator-viewer-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackplaybookgenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackplaybookgenerators/status
  verbs:
  - get
