# permissions for end users to edit openstackdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackdeploy-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackdeploys/status
  verbs:
  - get
