parameter_defaults:
{{- range $key, $value := .HostnameFormat }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- range $key, $value := .RoleCount }}
  {{ $key }}: {{ $value }}
{{- end }}
  HostnameMap:
  {{- range $key, $value := .HostnameMap }}
    {{ $key }}: {{ $value }}
  {{- end }}
