/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Generated by:
//
// operator-sdk create webhook --group osp-director --version v1beta1 --kind OpenStackNet --defaulting --programmatic-validation
//

package v1beta1

import (
	"fmt"

	"github.com/nmstate/kubernetes-nmstate/api/shared"
	"github.com/openstack-k8s-operators/osp-director-operator/pkg/nmstate"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// log is for logging in this package.
var openstacknetlog = logf.Log.WithName("openstacknet-resource")

// SetupWebhookWithManager - register this webhook with the controller manager
func (r *OpenStackNet) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-osp-director-openstack-org-v1beta1-openstacknet,mutating=true,failurePolicy=fail,sideEffects=None,groups=osp-director.openstack.org,resources=openstacknets,verbs=create;update,versions=v1beta1,name=mopenstacknet.kb.io,admissionReviewVersions={v1,v1beta1}

var _ webhook.Defaulter = &OpenStackNet{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *OpenStackNet) Default() {
	openstacknetlog.Info("default", "name", r.Name)

	// To avoid validation errors, we need to set the DesiredState to {} if it is nil.
	// This is the error that occurs otherwise...
	//
	// spec.attachConfiguration.nodeNetworkConfigurationPolicy.desiredState:
	// Invalid value: "null": spec.attachConfiguration.nodeNetworkConfigurationPolicy.desiredState in body must be of type object: "null"
	//
	if r.Spec.AttachConfiguration.NodeNetworkConfigurationPolicy.DesiredState.Raw == nil {
		r.Spec.AttachConfiguration.NodeNetworkConfigurationPolicy.DesiredState = shared.NewState("{}")
	}
}

//+kubebuilder:webhook:path=/validate-osp-director-openstack-org-v1beta1-openstacknet,mutating=false,failurePolicy=fail,sideEffects=None,groups=osp-director.openstack.org,resources=openstacknets,verbs=create;update,versions=v1beta1,name=vopenstacknet.kb.io,admissionReviewVersions={v1,v1beta1}

var _ webhook.Validator = &OpenStackNet{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackNet) ValidateCreate() error {
	openstacknetlog.Info("validate create", "name", r.Name)

	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackNet) ValidateUpdate(old runtime.Object) error {
	openstacknetlog.Info("validate update", "name", r.Name)

	return r.checkBridgeName(old)
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackNet) ValidateDelete() error {
	openstacknetlog.Info("validate delete", "name", r.Name)

	return nil
}

func (r *OpenStackNet) checkBridgeName(old runtime.Object) error {
	// Get the current (potentially new) bridge name, if any
	curBridge, err := nmstate.GetDesiredStatedBridgeName(r.Spec.AttachConfiguration.NodeNetworkConfigurationPolicy.DesiredState.Raw)

	if err != nil {
		return err
	}

	// Get the old bridge name, if any
	var ok bool
	var oldInstance *OpenStackNet

	if oldInstance, ok = old.(*OpenStackNet); !ok {
		return fmt.Errorf("Runtime object is not an OpenStackNet")
	}

	oldBridge, err := nmstate.GetDesiredStatedBridgeName(oldInstance.Spec.AttachConfiguration.NodeNetworkConfigurationPolicy.DesiredState.Raw)

	if err != nil {
		return err
	}

	if curBridge != oldBridge {
		return fmt.Errorf("Bridge names may not be changed")
	}

	return nil
}
