/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Generated by:
//
// operator-sdk create webhook --group osp-director --version v1beta1 --kind OpenStackBackup --programmatic-validation
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// log is for logging in this package.
var openstackbackuplog = logf.Log.WithName("openstackbackup-resource")

// SetupWebhookWithManager -
func (r *OpenStackBackup) SetupWebhookWithManager(mgr ctrl.Manager) error {
	if webhookClient == nil {
		webhookClient = mgr.GetClient()
	}

	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/validate-osp-director-openstack-org-v1beta1-openstackbackup,mutating=false,failurePolicy=fail,sideEffects=None,groups=osp-director.openstack.org,resources=openstackbackups,verbs=create;update,versions=v1beta1,name=vopenstackbackup.kb.io,admissionReviewVersions={v1},sideEffects=None

var _ webhook.Validator = &OpenStackBackup{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackBackup) ValidateCreate() error {
	openstackbackuplog.Info("validate create", "name", r.Name)

	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackBackup) ValidateUpdate(old runtime.Object) error {
	openstackbackuplog.Info("validate update", "name", r.Name)

	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackBackup) ValidateDelete() error {
	openstackbackuplog.Info("validate delete", "name", r.Name)

	return nil
}
