/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Generated by:
//
// operator-sdk create webhook --group osp-director --version v1beta1 --kind OpenStackNet --defaulting --programmatic-validation
//

package v1beta1

import (
	"fmt"
	"strings"

	"github.com/openstack-k8s-operators/osp-director-operator/api/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// log is for logging in this package.
var openstacknetlog = logf.Log.WithName("openstacknet-resource")

// SetupWebhookWithManager - register this webhook with the controller manager
func (r *OpenStackNet) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-osp-director-openstack-org-v1beta1-openstacknet,mutating=true,failurePolicy=fail,sideEffects=None,groups=osp-director.openstack.org,resources=openstacknets,verbs=create;update,versions=v1beta1,name=mopenstacknet.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &OpenStackNet{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *OpenStackNet) Default() {
	openstacknetlog.Info("default", "name", r.Name)

	//
	// The OpenStackNet "XYZ" is invalid: spec.routes: Invalid value: "null": spec.routes in body must be of type array: "null"
	//
	if r.Spec.Routes == nil {
		r.Spec.Routes = []Route{}
	}

	//
	// The OpenStackNet "XYZ" is invalid: spec.roleReservations: Invalid value: "null": spec.roleReservations in body must be of type object: "null"
	//
	if r.Spec.RoleReservations == nil {
		r.Spec.RoleReservations = map[string]OpenStackNetRoleReservation{}
	}

	//
	// The default domain name if non specified
	//
	if r.Spec.DomainName == "" {
		r.Spec.DomainName = fmt.Sprintf("%s.%s", strings.ToLower(r.Spec.Name), DefaultDomainName)
	}
}

//+kubebuilder:webhook:path=/validate-osp-director-openstack-org-v1beta1-openstacknet,mutating=false,failurePolicy=fail,sideEffects=None,groups=osp-director.openstack.org,resources=openstacknets,verbs=create;update;delete,versions=v1beta1,name=vopenstacknet.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &OpenStackNet{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackNet) ValidateCreate() error {
	openstacknetlog.Info("validate create", "name", r.Name)

	return checkBackupOperationBlocksAction(r.Namespace, shared.APIActionCreate)
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackNet) ValidateUpdate(old runtime.Object) error {
	openstacknetlog.Info("validate update", "name", r.Name)

	// Get the old bridge name, if any
	var ok bool
	var oldInstance *OpenStackNet

	if oldInstance, ok = old.(*OpenStackNet); !ok {
		return fmt.Errorf("runtime object is not an OpenStackNet")
	}

	//
	// create map with ip <-> hostname of the spec.RoleReservations
	//
	netReservations := map[string]string{}
	for _, role := range oldInstance.Spec.RoleReservations {
		for _, res := range role.Reservations {
			netReservations[res.IP] = res.Hostname
		}
	}

	//
	// verify that there is not a duplicate ip reservation in spec.RoleReservations
	//
	for _, role := range r.Spec.RoleReservations {
		for _, res := range role.Reservations {
			if hostname, ok := netReservations[res.IP]; ok &&
				res.Hostname != hostname {
				return fmt.Errorf("duplicate ip reservation for %s (%s,%s) on %s %s",
					res.IP,
					res.Hostname,
					hostname,
					r.Kind,
					r.Spec.NameLower,
				)
			}
		}
	}

	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *OpenStackNet) ValidateDelete() error {
	openstacknetlog.Info("validate delete", "name", r.Name)

	return checkBackupOperationBlocksAction(r.Namespace, shared.APIActionDelete)
}
