/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Generated by:
//
// operator-sdk create webhook --group osp-director --version v1beta1 --kind OpenStackNet --defaulting
//

package v1beta1

import (
	"github.com/nmstate/kubernetes-nmstate/api/shared"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

var openstacknetlog = logf.Log.WithName("openstacknet-resource")

// SetupWebhookWithManager - register this webhook with the controller manager
func (r *OpenStackNet) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

// +kubebuilder:webhook:path=/mutate-osp-director-openstack-org-v1beta1-openstacknet,mutating=true,failurePolicy=fail,groups=osp-director.openstack.org,resources=openstacknets,verbs=create;update,versions=v1beta1,name=mopenstacknet.kb.io

var _ webhook.Defaulter = &OpenStackNet{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *OpenStackNet) Default() {
	openstacknetlog.Info("default", "name", r.Name)

	// To avoid validation errors, we need to set the DesiredState to {} if it is nil.
	// This is the error that occurs otherwise...
	//
	// spec.attachConfiguration.nodeNetworkConfigurationPolicy.desiredState:
	// Invalid value: "null": spec.attachConfiguration.nodeNetworkConfigurationPolicy.desiredState in body must be of type object: "null"
	//
	if r.Spec.AttachConfiguration.NodeNetworkConfigurationPolicy.DesiredState.Raw == nil {
		r.Spec.AttachConfiguration.NodeNetworkConfigurationPolicy.DesiredState = shared.NewState("{}")
	}
}
